# Generated by Django 3.1.5 on 2021-03-01 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='news',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
