# Generated by Django 3.1.5 on 2021-02-08 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0010_comment_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karma', models.CharField(max_length=3)),
                ('about', models.TextField()),
                ('showdead', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('nopro', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
