# Generated by Django 3.1.5 on 2021-02-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20210210_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='now',
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
