# Generated by Django 3.1.5 on 2021-02-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_replaycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='karma',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
