# Generated by Django 3.1.5 on 2021-02-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20210217_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='karma',
            field=models.CharField(default=1, max_length=3),
        ),
    ]
