# Generated by Django 3.1.5 on 2021-02-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20210210_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='now',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
