# Generated by Django 3.1.5 on 2021-02-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
